### ISSUE TITLE
Do not reload page when "Add to favorite" button is clicked or item is unhearted on home page

### ISSUE THREAD

**Issue by EgorDP** [cse110-fa21-group22/cse110-fa21-group22#314]

**Comment by samanthaylin3** [comment]
I thought we wanted it to reload?

**Comment by DanlandYZ** [comment]
Reloading is there because we did not know how to refresh favorote-section on home page, 
I will try to fix it to not refresh on homepage, and it should only refresh the favorite-section on homepage
